# Generated by Django 5.1.4 on 2025-12-22 00:04

import django.core.validators
import profile_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='JPG/PNG/JPEG', upload_to=profile_manager.models.avatar_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, choices=[('UA', 'Ukraine'), ('US', 'United States'), ('IT', 'Italy')], default='UA', max_length=2, verbose_name='Preferred Cuisine / Region'),
        ),
    ]
