# Generated by Django 5.1.4 on 2026-04-30 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_manager', '0002_remove_profile_bio_remove_profile_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
    ]
