services:
  db:
    image: postgres:15-alpine
    container_name: tastebook_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
    ports:
      - "5433:5432"

  redis:
    image: redis:alpine
    container_name: tastebook_redis
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: tastebook_web
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery:
    build: .
    container_name: tastebook_celery
    command: celery -A favourite_tastebook worker -l INFO
    volumes:
      - .:/app
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - web

volumes:
  postgres_data: