# Generated by Django 5.1.4 on 2026-01-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_manager', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_photos/'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='importance',
            field=models.CharField(choices=[('required', 'required'), ('secondary', 'secondary'), ('optional', 'optional')], default='required', max_length=12),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('l', 'l'), ('pcs', 'pcs'), ('tbsp', 'tbsp'), ('tsp', 'tsp'), ('pinch', 'pinch')], default='g', max_length=10),
        ),
    ]
