# Generated by Django 5.1.4 on 2025-03-06 16:29

import json
import os
from django.db import migrations

def load_ingredients(apps, schema_editor):
    Ingredient = apps.get_model('recipe_manager', 'Ingredient')
    file_path = os.path.join(os.path.dirname(__file__), 'data', 'ingredients.json')

    with open(file_path, encoding='utf-8') as f:
        data = json.load(f)
        ingredients = [Ingredient(pk=item["pk"], name=item["name"], category=item["category"]) for item in data]
        Ingredient.objects.bulk_create(ingredients, ignore_conflicts=True)

def load_recipes(apps, schema_editor):
    Recipe = apps.get_model('recipe_manager', 'Recipe')
    Ingredient = apps.get_model('recipe_manager', 'Ingredient')
    RecipeIngredient = apps.get_model('recipe_manager', 'RecipeIngredient')

    file_path = os.path.join(os.path.dirname(__file__), 'data', 'recipes.json')

    with open(file_path, encoding='utf-8') as f:
        recipes_data = json.load(f)
        for item in recipes_data:
            recipe = Recipe.objects.create(
                pk=item["pk"],
                name=item["name"],
                cook_time=item["cook_time"], # <---- Убедись, что cook_time есть в recipes.json
                instructions=item["instructions"]
            )
            for ingredient_item in item["ingredients"]:
                ingredient_pk = ingredient_item["pk"]
                weight = ingredient_item.get("weight", 1)

                try:
                    ingredient = Ingredient.objects.get(pk=ingredient_pk)
                    RecipeIngredient.objects.create(
                        recipe=recipe,
                        ingredient=ingredient,
                        weight=weight
                    )
                except Ingredient.DoesNotExist:
                    print(f"Ingredient with pk={ingredient_pk} not found. Recipe: {recipe.name}")


def load_dishes(apps, schema_editor):
    Dish = apps.get_model('recipe_manager', 'Dish')
    Recipe = apps.get_model('recipe_manager', 'Recipe')
    file_path = os.path.join(os.path.dirname(__file__), 'data', 'dishes.json')

    with open(file_path, encoding='utf-8') as f:
        data = json.load(f)
        for item in data:
            try:
                recipe = Recipe.objects.get(pk=item["recipe_pk"])
                Dish.objects.create(
                    pk=item["pk"],
                    name=item["name"],
                    recipe=recipe # Assign Recipe using ForeignKey
                    # description=item["description"],  <---- УДАЛИЛ description!
                )
            except Recipe.DoesNotExist:
                print(f"Recipe with pk={item['recipe_pk']} not found. Dish: {item['name']}")


def reverse_migration(apps, schema_editor):
    Ingredient = apps.get_model('recipe_manager', 'Ingredient')
    Recipe = apps.get_model('recipe_manager', 'Recipe')
    Dish = apps.get_model('recipe_manager', 'Dish')

    Dish.objects.all().delete()
    Recipe.objects.all().delete()
    Ingredient.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_manager', '0002_remove_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.RunPython(load_ingredients, reverse_code=reverse_migration),
        migrations.RunPython(load_recipes, reverse_code=reverse_migration),
        migrations.RunPython(load_dishes, reverse_code=reverse_migration),
    ]
