# Generated by Django 5.1.4 on 2026-01-29 20:25

from django.db import migrations

#created full image path's for every recipe
def reload_fixtures(apps, schema_editor):
    from django.core.management import call_command
    call_command('loaddata', 'recipes/01_ukrainian.json')
    call_command('loaddata', 'recipes/02_common.json')
    call_command('loaddata', 'recipes/03_italian.json')

class Migration(migrations.Migration):
    dependencies = [('recipe_manager', '0003_alter_recipe_image_url_and_more')]
    operations = [migrations.RunPython(reload_fixtures, reverse_code=migrations.RunPython.noop)]