# Generated by Django 5.1.4 on 2026-02-03 18:09

from django.db import migrations


def reload_fixtures(apps, schema_editor):
    from django.core.management import call_command
    import logging

    logger = logging.getLogger(__name__)

    fixtures = [
        'cuisines/cuisines.json',
        'ingredients/01_ing.json',
        'recipes/01_ukrainian.json',
        'recipes/02_common.json',
        'recipes/03_italian.json',
        'recipes/04_american.json',
        'recipe_ingredients/01_ukr.json',
        'recipe_ingredients/02_cmn.json',
        'recipe_ingredients/03_itl.json',
        'recipe_ingredients/04_amrk.json'
    ]

    for fixture in fixtures:
        try:
            call_command('loaddata', fixture)
            print(f"Successfully loaded {fixture}")
        except Exception as e:
            print(f"⚠️ WARNING: Failed to load {fixture}: {str(e)}")


class Migration(migrations.Migration):
    dependencies = [('recipe_manager', '0004_savedrecipe')]
    operations = [
        migrations.RunPython(reload_fixtures, reverse_code=migrations.RunPython.noop)
    ]