# Generated by Django 5.1.4 on 2026-02-03 18:09


from django.db import migrations


def reload_fixtures(apps, schema_editor):
    from django.core.management import call_command

    call_command('loaddata', 'cuisines/cuisines.json')
    call_command('loaddata', 'ingredients/01_ing.json')

    call_command('loaddata', 'recipes/01_ukrainian.json')
    call_command('loaddata', 'recipes/02_common.json')
    call_command('loaddata', 'recipes/03_italian.json')
    call_command('loaddata', 'recipes/04_american.json')

    call_command('loaddata', 'recipe_ingredients/01_ukr.json')
    call_command('loaddata', 'recipe_ingredients/02_cmn.json')
    call_command('loaddata', 'recipe_ingredients/03_itl.json')
    call_command('loaddata', 'recipe_ingredients/04_amrk.json')


class Migration(migrations.Migration):
    dependencies = [('recipe_manager', '0004_savedrecipe')]
    operations = [migrations.RunPython(reload_fixtures, reverse_code=migrations.RunPython.noop)]
