# Generated by Django 5.1.4 on 2026-04-30 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_manager', '0006_savedrecipe_is_favorite_usertastepreference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCuisinePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField(choices=[(-2, 'Hate'), (-1, 'Do not like'), (0, 'Indifferent'), (1, 'Like'), (2, 'Love')], default=0)),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favored_by_users', to='recipe_manager.cuisine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuisine_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Cuisine Preference',
                'unique_together': {('user', 'cuisine')},
            },
        ),
    ]
