# Generated by Django 5.1.4 on 2026-08-31 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_manager', '0007_usercuisinepreference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cuisine', models.CharField(blank=True, max_length=100)),
                ('cook_time', models.PositiveIntegerField(help_text='Time in minutes')),
                ('steps', models.JSONField(default=list)),
                ('session_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Generated Recipe',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'title')},
            },
        ),
        migrations.CreateModel(
            name='GeneratedRecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unit', models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('l', 'l'), ('pcs', 'pcs'), ('tbsp', 'tbsp'), ('tsp', 'tsp'), ('pinch', 'pinch')], default='g', max_length=10)),
                ('importance', models.CharField(choices=[('required', 'required'), ('secondary', 'secondary'), ('optional', 'optional')], default='required', max_length=12)),
                ('generated_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipe_manager.generatedrecipe')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_generated_recipes', to='recipe_manager.ingredient')),
            ],
            options={
                'verbose_name': 'Ingredient using in generated recipe',
                'unique_together': {('generated_recipe', 'ingredient')},
            },
        ),
    ]
