# Generated by Django 5.1.4 on 2026-09-01 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_manager', '0008_generatedrecipe_generatedrecipeingredient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_tastes', models.BooleanField(default=True)),
                ('recipe_source', models.CharField(choices=[('database', 'Our recipe database'), ('ai', 'Composed by the assistant only')], default='database', max_length=16)),
                ('autosave_drafts', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assistant Preference',
            },
        ),
    ]
