# Generated by Django 5.1.4 on 2026-09-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_manager', '0009_agentpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedrecipe',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
